import type { Subscription } from "../types";

export const subscriptions: Subscription[] = [
  {
    id: "1",
    name: "Adobe Creative Cloud",
    category: "Design",
    price: 52.99,
    billingCycle: "Monthly",
    nextRenewal: "May 15, 2025",
    logo: "/placeholder.svg?height=40&width=40",
    status: "Active",
  },
  {
    id: "2",
    name: "Slack",
    category: "Communication",
    price: 12.5,
    billingCycle: "Monthly",
    nextRenewal: "May 18, 2025",
    logo: "/placeholder.svg?height=40&width=40",
    status: "Active",
  },
  {
    id: "3",
    name: "AWS",
    category: "Cloud Services",
    price: 432.18,
    billingCycle: "Monthly",
    nextRenewal: "May 20, 2025",
    logo: "/placeholder.svg?height=40&width=40",
    status: "Active",
  },
  {
    id: "4",
    name: "Google Workspace",
    category: "Productivity",
    price: 138.0,
    billingCycle: "Monthly",
    nextRenewal: "June 1, 2025",
    logo: "/placeholder.svg?height=40&width=40",
    status: "Active",
  },
  {
    id: "5",
    name: "Salesforce",
    category: "CRM",
    price: 150.0,
    billingCycle: "Monthly",
    nextRenewal: "June 5, 2025",
    logo: "/placeholder.svg?height=40&width=40",
    status: "Active",
  },
  {
    id: "6",
    name: "Microsoft 365",
    category: "Productivity",
    price: 99.99,
    billingCycle: "Monthly",
    nextRenewal: "June 10, 2025",
    logo: "/placeholder.svg?height=40&width=40",
    status: "Active",
  },
  {
    id: "7",
    name: "Zoom",
    category: "Communication",
    price: 14.99,
    billingCycle: "Monthly",
    nextRenewal: "June 15, 2025",
    logo: "/placeholder.svg?height=40&width=40",
    status: "Active",
  },
  {
    id: "8",
    name: "ChatGPT Plus",
    category: "AI",
    price: 20.0,
    billingCycle: "Monthly",
    nextRenewal: "June 20, 2025",
    logo: "/placeholder.svg?height=40&width=40",
    status: "Active",
  },
  {
    id: "9",
    name: "Claude Pro",
    category: "AI",
    price: 20.0,
    billingCycle: "Monthly",
    nextRenewal: "June 22, 2025",
    logo: "/placeholder.svg?height=40&width=40",
    status: "Active",
  },
  {
    id: "10",
    name: "Leonardo AI",
    category: "AI",
    price: 22.0,
    billingCycle: "Monthly",
    nextRenewal: "June 25, 2025",
    logo: "/placeholder.svg?height=40&width=40",
    status: "Active",
  },
  // ... rest of the subscriptions data
];
